sudo: required
services:
  - docker

before_install:
  - docker build -t dshaevel/docker-react -f Dockerfile.dev .

script:
  - docker run dshaevel/docker-react yarn test --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-833610576391"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"